{% set name = "xeus-octave" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/chickadee-engineering/jupyter-xeus/xeus-octave.git
  git_rev: e7c5d9469650f7c73d1f924fe632363a13315ce4
  git_depth: 1

build:
  number: 6
  skip: true  # [win]

requirements:
  build:
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - octave 9.*
    - xorg-libxfixes  # [linux]
    - glfw
    - glad
    - libpng
    - xeus-zmq >=1.0,<1.2
    - nlohmann_json =3.11.2
    - cppzmq
    - xtl >=0.7,<1.0
    - xproperty

  run:
    - glfw
    - glad
    - xeus
    - zeromq
    # Octave is missing a run_exports section
    - {{ pin_compatible('octave', max_pin='x.x') }}
    # Mesalib is missing a run_exports section
    - {{ pin_compatible('mesalib', max_pin='x.x') }}

test:
  requires:
    - jupyter_kernel_test >=0.4.3
    - nbval
    - pytest
    - pytest-rerunfailures
    # - {{ cdt('xorg-x11-server-xvfb') }}     # [linux]
  source_files:
    - test
  commands:
    - test -f ${PREFIX}/bin/xoctave  # [unix]
    - xoctave --version
    - pytest test -k 'not plot'
    - pytest test -k 'plot_plotly'
    # - xvfb-run pytest test -k 'plot_notebook'  # [linux]

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'Xeus kernel for Octave'

  description: |
    Xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools Octave.

extra:
  recipe-maintainers:
    - rapgenic
    - marimeireles
    - SylvainCorlay
    - AntoinePrv
